function FindProxyForURL(url, host) {
  // STRICT_JO_PLUS (IPv4) — generated by build_strict_jo_plus_pac_v4.py
  var JO_PROXY_HOST = "127.0.0.1";
  var PORT_LOBBY = 10010;
  var PORT_MATCH = 20001;
  var PORT_RECRUIT_SEARCH = 12000;
  var PORT_UPDATES = 8080;
  var PORT_CDN = 443;
  var STICKY_MINUTES = 10;

  var JO_V4_PREFIXES = [
    "5.45.141.0/24",
    "37.17.194.0/24",
    "37.17.204.0/24",
    "37.123.76.0/22",
    "37.123.93.0/24",
    "37.202.76.0/22",
    "37.202.80.0/20",
    "37.202.103.0/24",
    "37.202.112.0/20",
    "37.220.115.0/24",
    "46.32.96.0/24",
    "46.185.140.0/22",
    "46.185.144.0/20",
    "46.185.160.0/19",
    "46.185.192.0/24",
    "46.185.204.0/22",
    "46.185.208.0/20",
    "46.185.224.0/19",
    "46.248.196.0/24",
    "46.248.204.0/22",
    "46.248.208.0/20",
    "62.72.172.0/22",
    "62.72.178.0/24",
    "62.72.182.0/23",
    "62.72.184.0/21",
    "79.134.140.0/22",
    "79.173.215.0/24",
    "79.173.230.0/23",
    "79.173.232.0/21",
    "81.28.114.0/24",
    "82.212.65.0/24",
    "82.212.108.0/24",
    "84.18.38.0/23",
    "84.18.41.0/24",
    "84.18.42.0/23",
    "84.18.46.0/23",
    "84.18.48.0/20",
    "84.18.67.0/24",
    "84.18.76.0/22",
    "84.18.80.0/23",
    "84.18.92.0/24",
    "86.108.19.0/24",
    "86.108.46.0/24",
    "86.108.73.0/24",
    "86.108.125.0/24",
    "91.186.236.0/22",
    "91.186.240.0/20",
    "92.241.36.0/24",
    "92.241.44.0/22",
    "92.253.3.0/24",
    "92.253.12.0/22",
    "92.253.16.0/20",
    "92.253.32.0/19",
    "92.253.64.0/18",
    "94.142.58.0/24",
    "94.249.0.0/23",
    "94.249.2.0/24",
    "94.249.4.0/22",
    "94.249.8.0/21",
    "94.249.16.0/20",
    "94.249.32.0/20",
    "94.249.48.0/21",
    "94.249.56.0/22",
    "94.249.60.0/24",
    "94.249.80.0/24",
    "94.249.86.0/23",
    "94.249.88.0/21",
    "94.249.96.0/22",
    "94.249.100.0/24",
    "94.249.110.0/24",
    "94.249.118.0/23",
    "94.249.120.0/21",
    "95.172.204.0/22",
    "109.107.249.0/24",
    "109.237.193.0/24",
    "109.237.204.0/22",
    "149.200.147.0/24",
    "149.200.148.0/22",
    "149.200.152.0/21",
    "149.200.160.0/19",
    "149.200.205.0/24",
    "149.200.217.0/24",
    "149.200.218.0/23",
    "149.200.220.0/22",
    "149.200.237.0/24",
    "149.200.247.0/24",
    "149.200.248.0/21",
    "176.28.140.0/22",
    "176.28.144.0/20",
    "176.28.160.0/19",
    "176.28.192.0/18",
    "176.29.12.0/22",
    "176.29.16.0/20",
    "176.29.32.0/19",
    "176.29.64.0/18",
    "176.29.128.0/17",
    "176.57.0.0/24",
    "176.57.2.0/23",
    "176.57.4.0/22",
    "176.57.8.0/21",
    "176.57.16.0/24",
    "176.57.24.0/21",
    "178.77.140.0/22",
    "178.77.144.0/20",
    "178.77.183.0/24",
    "178.77.184.0/21",
    "178.238.180.0/24",
    "188.123.179.0/24",
    "188.247.69.0/24",
    "188.247.84.0/23",
    "193.188.95.0/24",
    "212.34.1.0/24",
    "212.34.2.0/23",
    "212.34.4.0/22",
    "212.34.9.0/24",
    "212.34.12.0/24",
    "212.34.19.0/24",
    "212.35.67.0/24",
    "212.35.68.0/24",
    "212.35.75.0/24",
    "212.35.76.0/22",
    "212.35.92.0/24",
    "212.118.0.0/24",
    "212.118.25.0/24",
    "213.139.44.0/22",
    "213.139.48.0/20",
    "213.186.172.0/22",
    "213.186.176.0/20",
    "217.23.32.0/24",
    "217.23.44.0/22",
    "217.29.241.0/24"
  ];

  function proxyLine(port) { return "SOCKS5 " + JO_PROXY_HOST + ":" + port; }
  function matchDomain(host,list){ for(var i=0;i<list.length;i++){var pat=list[i]; if(pat.indexOf("*")>=0){ if(shExpMatch(host,pat)) return true; } else { if(dnsDomainIs(host,pat)) return true; } } return false; }
  function matchURL(url,patterns){ for(var i=0;i<patterns.length;i++) if(shExpMatch(url,patterns[i])) return true; return false; }
  var PUBG_DOMAINS = {
    LOBBY: ["*.pubgmobile.com","*.pubgmobile.net","*.proximabeta.com","*.igamecj.com"],
    MATCH: ["*.gcloud.qq.com","gpubgm.com","*.igamecj.com","*.proximabeta.com"],
    RECRUIT_SEARCH: ["match.igamecj.com","match.proximabeta.com","teamfinder.igamecj.com","teamfinder.proximabeta.com","clan.igamecj.com"],
    UPDATES: ["cdn.pubgmobile.com","updates.pubgmobile.com","patch.igamecj.com","hotfix.proximabeta.com","dlied1.qq.com","dlied2.qq.com"],
    CDNs: ["cdn.igamecj.com","cdn.proximabeta.com","cdn.tencentgames.com","*.qcloudcdn.com","*.cloudfront.net","*.edgesuite.net"]
  };
  var URL_PATTERNS = {
    LOBBY: ["*/account/login*","*/client/version*","*/status/heartbeat*","*/presence/*","*/friends/*"],
    MATCH: ["*/matchmaking/*","*/mms/*","*/game/start*","*/game/join*","*/report/battle*"],
    RECRUIT_SEARCH: ["*/teamfinder/*","*/clan/*","*/social/*","*/search/*","*/recruit/*"],
    UPDATES: ["*/patch*","*/update*","*/hotfix*","*/download*","*/assets/*","*/assetbundle*","*/obb*"],
    CDNs: ["*/cdn/*","*/image/*","*/media/*","*/video/*","*/res/*","*/pkg/*"]
  };

  function ip4ToInt(ip){ var p=ip.split('.'); return ((p[0]<<24)>>>0) + (p[1]<<16) + (p[2]<<8) + (p[3]>>>0); }
  function inCidrV4(ip,cidr){ var parts=cidr.split('/'); var base=parts[0]; var bits=parts.length>1?parseInt(parts[1],10):32; var ipi=ip4ToInt(ip); var bi=ip4ToInt(base); var mask = bits===0?0: (~((1<<(32-bits))-1))>>>0; return (ipi & mask) === (bi & mask); }
  function isJordanIPv4(ip){ if(!ip) return false; for(var i=0;i<JO_V4_PREFIXES.length;i++) if(inCidrV4(ip, JO_V4_PREFIXES[i])) return true; return false; }

  // Sticky cache
  if (typeof _stickyCache === "undefined") { var _stickyCache = {}; }
  function nowMin(){ return Math.floor((new Date()).getTime() / 60000); }
  function stickyGet(h){ var e=_stickyCache[h]; if(!e) return null; if (nowMin()-e.t > STICKY_MINUTES) return null; return e.v; }
  function stickyPut(h,v){ _stickyCache[h] = {t: nowMin(), v: v}; }

  // Quick outs
  var YT = ["youtube.com","youtu.be","googlevideo.com","ytimg.com","youtube-nocookie.com"];
  if (matchDomain(host, YT)) return "DIRECT";

  var cached = stickyGet(host);
  if (cached) return cached;

  var destIP = dnsResolve(host);
  var joV4 = isJordanIPv4(destIP);

  function inCategory(cat){ return matchDomain(host,PUBG_DOMAINS[cat]) || matchURL(url, URL_PATTERNS[cat]); }
  function decideForCategory(cat, defaultPort){ if (joV4) { stickyPut(host,"DIRECT"); return "DIRECT"; } var line = proxyLine(defaultPort); stickyPut(host, line); return line; }

  if (inCategory("MATCH")) return decideForCategory("MATCH", PORT_MATCH);
  if (inCategory("RECRUIT_SEARCH")) return decideForCategory("RECRUIT_SEARCH", PORT_RECRUIT_SEARCH);
  if (inCategory("LOBBY")) return decideForCategory("LOBBY", PORT_LOBBY);

  if (inCategory("UPDATES")) { if (joV4) { stickyPut(host,"DIRECT"); return "DIRECT"; } var u = proxyLine(PORT_UPDATES); stickyPut(host,u); return u; }
  if (inCategory("CDNs")) { if (joV4) { stickyPut(host,"DIRECT"); return "DIRECT"; } var c = proxyLine(PORT_CDN); stickyPut(host,c); return c; }

  if (joV4) { stickyPut(host,"DIRECT"); return "DIRECT"; }
  var fb = proxyLine(PORT_LOBBY); stickyPut(host, fb); return fb;
}
